Add support for dynamically selecting image architecture.
cloudposse/terraform-aws-eks-workers pull request #61
Opened 2021-04-09 08:04 UTC by haad

## what
* This PR will add support for selecting ami architecture.  I have added `eks_worker_ami_arch_filter` variable with default x86_64 and possibe options i386, x86_64 and arm64. This is required for eks graviton workers.

2021-04-10 22:29 UTC, Gowiem approved these changes

2021-04-10 22:29 UTC, Gowiem commented
/test all

2021-04-11 02:29 UTC, Gowiem commented
/rebuild-readme

2021-04-11 17:48 UTC, Gowiem commented
/test all

2021-04-11 17:50 UTC, Gowiem commented
@haad looks like our CI is having issues. Can you run the following locally and then we'll get this merged?

```bash
make init
make pr/auto-format
```

Push the result and ping me and I'll get this reviewed and merged. Thanks for the help!

2021-04-12 03:02 UTC, Nuru requested changes
@haad How necessary is this? Up until now we have been able to filter AMIs via `var.eks_worker_ami_name_regex`.

Also, if we do need it, then for consistency with [eks-node-group](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_node_group) please use the `ami_type` variable from [terraform-aws-eks-node-group](https://github.com/cloudposse/terraform-aws-eks-node-group/blob/61ac9304b3f4e7383639fdca4712a4580535f461/variables.tf#L81-L94) (you can name it `eks_worker_ami_type`) and be sure to include validation

2021-04-16 19:55 UTC, martinhaus commented
Using these values should be enough to filter out the ARM64 images
```
  eks_worker_ami_name_filter = "amazon-eks-arm64-node-${var.eks_kubernetes_version}*"
  eks_worker_ami_name_regex  = "^amazon-eks-arm64-node-[1-9,.]+-v[0-9]{8}$"
```

2021-04-17 18:26 UTC, Nuru commented
Closing as [not needed](https://github.com/cloudposse/terraform-aws-eks-workers/pull/61#issuecomment-821527931), won't do

2021-04-17 18:26 UTC, closed without merging